#! /bin/bash

module load apps/pythonpackages/3.6.0/keras/2.2.2/gpu
module load pythonpackages/3.6.0/pandas/0.23.4/gnu
module load pythonpackages/3.6.0/numpy/1.15.0/gnu

python3 ./lenet.py "col341_a3_data/devnagri_train.csv" "col341_a3_data/devnagri_test_public.csv" "cs5160789_run_0" "0"
python3 ./lenet.py "col341_a3_data/devnagri_train.csv" "col341_a3_data/devnagri_test_public.csv" "cs5160789_run_1" "1"